[package]
name = "tokenmill-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tokenmill-core = { path = "../tokenmill-core" }
clap     = { version = "4", features = ["derive"] }
anyhow   = "1"
indicatif = "0.17"    # progress bars
ratatui = "0.26"
crossterm = { version = "0.27", features = ["event-stream"] }
sysinfo = "0.30"
hf-hub = "0.3"
