[package]
name = "tokenmill-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde        = { version = "1", features = ["derive"] }
serde_json   = "1"
rayon        = "1"
xxhash-rust  = { version = "0.8", features = ["xxh3"] }
rand         = "0.8"
rand_chacha  = "0.3"
anyhow       = "1"
thiserror    = "1"
tiktoken-rs  = "0.5"
clap = { version = "4.6.0", features = ["derive"] }
arrow        = "58"
parquet      = { version = "58", features = ["arrow"] }
arrow-schema = "58"
candle-core = "0.10.2"
candle-nn = "0.10.2"
candle-transformers = "0.10.2"
tokenizers = "0.22.2"

[dev-dependencies]
tempfile     = "3"
